# Generated by Django 2.2.17 on 2020-11-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='title',
        ),
        migrations.AddField(
            model_name='customtext',
            name='a1233455',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
