# Generated by Django 2.2.17 on 2020-11-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201113_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hgfhfgfghfhg',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hgjhgjhg',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hjjgjhgjgh',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='jhgjhghjg',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='jhgjhgjgjhgfhjg',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='ytrtyrytryr',
        ),
    ]
