# Generated by Django 2.2.17 on 2020-11-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201113_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hgfjhgfkhfj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jhgjghjghjg', models.BigIntegerField()),
            ],
        ),
    ]
